import type { Metadata } from 'next';
import Image from 'next/image';
import Link from 'next/link';
import Script from 'next/script';
import '@fontsource/roboto/latin-700.css';
import '@fontsource/roboto/latin-500.css';
import '@fontsource/noto-sans/latin-400.css';
import '@fontsource/noto-sans/latin-600.css';
import './globals.css';
import { baseUrl, company } from '@/lib/content';
export const metadata: Metadata = {metadataBase:new URL(baseUrl),title:{default:'Vinn kommunala ramavtal | M-Anbud',template:'%s'},description:'Vi hjälper ditt företag att vinna kommunala ramavtal. Över 30 års erfarenhet, fasta priser och betalning efter inlämning.',openGraph:{type:'website',locale:'sv_SE',siteName:company.name,images:['/opengraph-image']},twitter:{card:'summary_large_image'}};
export default function Layout({children}:{children:React.ReactNode}){return <html lang="sv"><body><a className="skip" href="#main">Hoppa till innehållet</a><div className="topbar"><div className="wrap"><span>Upphandlingskunskap som får företag att växa.</span><a href={`tel:${company.tel}`}>{company.phone}</a></div></div><header><div className="wrap header-inner"><Link href="/" aria-label="M-Anbud Konsult AB – startsida" className="logo"><Image src="/logo.svg" alt="M-Anbud Konsult AB" width={200} height={63} priority unoptimized/></Link><nav aria-label="Huvudmeny"><Link href="/tjanster/">Tjänster</Link><Link href="/kundcase/">Kundcase</Link><Link href="/process/">Så går det till</Link><Link href="/om-oss/">Om oss</Link><Link href="/kontakt/" className="nav-contact">Prata med oss <span aria-hidden="true">↗</span></Link></nav></div></header><main id="main">{children}</main><footer><div className="wrap footer-grid"><div><Link href="/" className="footer-brand">M-Anbud<span>KONSULT AB</span></Link><p>Vi tar hand om anbudet.<br/>Du tar hand om ditt företag.</p></div><div><h2>Hitta rätt</h2><Link href="/tjanster/">Våra tjänster</Link><Link href="/kundcase/">Kundcase</Link><Link href="/fragor-svar/">Frågor & svar</Link><Link href="/kontakt/">Kontakt</Link></div><div><h2>Hör av dig</h2><a href={`tel:${company.tel}`}>{company.phone}</a><a href={`mailto:${company.email}`}>{company.email}</a><p>Mejl och telefon<br/>vardagar 8–17</p></div><div><h2>Här finns vi</h2><p>{company.address}<br/>{company.city}</p><a href={company.map} target="_blank" rel="noopener noreferrer">Visa på Google Maps ↗</a><p>Org.nr {company.org}</p></div></div><div className="wrap footer-bottom"><span>© {new Date().getFullYear()} M-Anbud Konsult AB</span><Link href="/integritet/">Integritetspolicy</Link><span>Stockholm · Mälardalen</span></div></footer>{process.env.NEXT_PUBLIC_PLAUSIBLE_SCRIPT_URL && <Script src={process.env.NEXT_PUBLIC_PLAUSIBLE_SCRIPT_URL} strategy="afterInteractive"/>}</body></html>}
