"use client";
import { useState } from 'react';
import Link from 'next/link';
import { Arrow } from '@/components/icons';
export default function ContactForm({enabled}:{enabled:boolean}){
 const [state,setState]=useState<'idle'|'sending'|'success'|'error'>('idle');
 const [message,setMessage]=useState('');
 const [errors,setErrors]=useState<Record<string,string>>({});
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(state==='sending')return;const form=e.currentTarget;const data=Object.fromEntries(new FormData(form));setErrors({});setState('sending');try{const response=await fetch('/api/contact/',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const result=await response.json();if(!response.ok){setErrors(result.errors||{});throw new Error(result.message||'Det gick inte att skicka. Ring eller mejla oss i stället.')}setState('success');setMessage('Tack för ditt meddelande. Vi hör av oss inom 24 timmar.');form.reset();}catch(err){setState('error');setMessage(err instanceof Error?err.message:'Det gick inte att skicka. Försök igen eller ring oss.')}}
 return <form onSubmit={submit} className="contact-form">{!enabled&&<p className="form-note">Vill du nå oss redan nu? Ring eller mejla oss direkt. Formuläret öppnar när vår mejltjänst är ansluten.</p>}<div className="form-fields">{[{name:'name',label:'Namn',type:'text',auto:'name',required:true},{name:'company',label:'Företag',type:'text',auto:'organization',required:false},{name:'phone',label:'Telefon',type:'tel',auto:'tel',required:false},{name:'email',label:'Mejl',type:'email',auto:'email',required:true}].map(f=><div className="field" key={f.name}><label htmlFor={f.name}>{f.label}{f.required?' *':''}</label><input id={f.name} name={f.name} type={f.type} autoComplete={f.auto} required={f.required} maxLength={f.name==='email'?254:120} aria-invalid={Boolean(errors[f.name])} aria-describedby={errors[f.name]?`${f.name}-error`:undefined}/>{errors[f.name]&&<p id={`${f.name}-error`} className="field-error">{errors[f.name]}</p>}</div>)}</div><div className="field"><label htmlFor="message">Meddelande *</label><textarea id="message" name="message" required minLength={10} maxLength={5000} rows={5} aria-invalid={Boolean(errors.message)} aria-describedby={errors.message?'message-error':undefined}/>{errors.message&&<p id="message-error" className="field-error">{errors.message}</p>}</div><div className="honeypot" aria-hidden="true"><label htmlFor="website">Lämna detta fält tomt</label><input id="website" name="website" tabIndex={-1} autoComplete="off"/></div><p className="form-privacy">Vi använder dina uppgifter för att svara på din förfrågan. <Link href="/integritet/">Så hanterar vi personuppgifter.</Link></p><button className="button" disabled={!enabled||state==='sending'}>{state==='sending'?'Skickar…':'Skicka meddelande'}<Arrow/></button><p role={state==='error'?'alert':'status'} aria-live="polite" className={`form-feedback ${state}`}>{message}</p></form>
}
